name: pomocoenv
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - pip
  - pip:
    - wheel
    - attrdict
    - numpy
    - pyserial
    - wxPython
    - configparser
    - pytest